return {
--     {
--         "3rd/image.nvim",
--         config = function()
--             require("image").setup({
--                 backend = "kitty", -- or "ueberzug" or "sixel"
--                 processor = "magick_cli", -- or "magick_rock"
--                 integrations = {
--                     markdown = {
--                         enabled = true,
--                         clear_in_insert_mode = false,
--                         download_remote_images = true,
--                         only_render_image_at_cursor = true,
--                         only_render_image_at_cursor_mode = "popup",
--                         floating_windows = true,
--                         filetypes = { "markdown", "vimwiki" },
--                     },
--                     typst = {
--                         enabled = true,
--                         filetypes = { "typst" },
--                     },
--                 },
--                 max_height_window_percentage = 50,
--             })
--         end
--     },
}
--
